services:
  mercure:
    image: dunglas/mercure
    restart: unless-stopped
    environment:
      # Uncomment the following line to disable HTTPS
      SERVER_NAME: ':80'
      MERCURE_PUBLISHER_JWT_KEY: "JapanChubuNagoyaOptimindLoogia111Pub"
      MERCURE_SUBSCRIBER_JWT_KEY: "JapanChubuNagoyaOptimindLoogia111Sub"
      MERCURE_EXTRA_DIRECTIVES: "cors_origins http://localhost:3000"
    # Uncomment the following line to enable the development mode
    #command: /usr/bin/caddy run --config /etc/caddy/dev.Caddyfile
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "https://localhost/healthz"]
      timeout: 5s
      retries: 5
      start_period: 60s
    ports:
      - "127.0.0.1:10380:80"
      # - "443:443"
    volumes:
      - mercure_data:/data
      - mercure_config:/config

volumes:
  mercure_data:
  mercure_config: